export const SET_USER = "SET_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_QUIZ = "GET_QUIZ"
export const GET_QUESTIONS = "GET_QUESTIONS"
export const SET_TAKER_EMAIL = "SET_TAKER_EMAIL"