export const GET_USERS = "GET_USERS"
export const SET_USER = "SET_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const POST_USER = "POST_USER"
export const GET_QUIZ = "GET_QUIZ"
export const GET_QUESTIONS = "GET_QUESTIONS"